name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r req.txt
    - name: Generate .env file
      run: |
        echo "SECRET_KEY='django-insecure-^_^!p6b20b&##6aq4^(ov)eosy98#=1x5=wig&&90hi)m$064q'" >> .env
        echo "EMAIL_HOST_USER='example@example.com'" >> .env
        echo "EMAIL_HOST_PASSWORD='pswwrd'" >> .env
        echo "EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'" >> .env
        echo "EMAIL_HOST='smtp.gmail.com'" >> .env
        echo "EMAIL_PORT='587'" >> .env
        echo "EMAIL_USE_TLS='True'" >> .env
    - name: Run Tests
      run: |
        python manage.py test
